INSERT INTO listings (title, description, salary, city, state, company, address, phone, email, requirements, tags, user_id) VALUES
('Software Engineer', 'We are seeking a skilled software engineer to develop high-quality software solutions.', 80000, 'San Francisco', 'CA', 'TechCorp Solutions', '123 Market Street, San Francisco, CA 94102', '(415) 555-0123', 'jobs@techcorp.com', 'Bachelor''s degree in Computer Science, 3+ years experience in Java/Python, knowledge of software development lifecycle', '["Software Development", "Java", "Python"]', 2),

('Marketing Specialist', 'We are looking for a marketing specialist to develop and implement effective marketing strategies.', 60000, 'New York', 'NY', 'Digital Marketing Pro', '456 Broadway, New York, NY 10013', '(212) 555-0456', 'careers@digitalmarketing.com', 'Bachelor''s degree in Marketing, 2+ years experience in digital marketing, proficiency in social media platforms and SEO tools', '["Digital Marketing", "Social Media", "SEO"]', 1),

('Accountant', 'We are hiring an experienced accountant to handle financial transactions and ensure compliance.', 55000, 'Chicago', 'IL', 'Financial Services Inc', '789 LaSalle Street, Chicago, IL 60601', '(312) 555-0789', 'hr@financialservices.com', 'CPA certification preferred, 3+ years experience in accounting, knowledge of financial reporting and bookkeeping principles', '["Accounting", "Bookkeeping", "Financial Reporting"]', 3),

('UX Designer', 'We are seeking a talented UX designer to create intuitive and visually appealing user interfaces.', 70000, 'Seattle', 'WA', 'Design Studio Northwest', '321 Pine Street, Seattle, WA 98101', '(206) 555-0321', 'talent@designstudio.com', 'Bachelor''s degree in Design or related field, 2+ years UX experience, proficiency in wireframing and prototyping tools, web development knowledge', '["User Experience", "Wireframing", "Prototyping", "Web Development"]', 1),

('Customer Service Representative', 'We are looking for a friendly customer service representative to assist customers and resolve issues.', 40000, 'New York', 'NY', 'Customer Care Central', '654 5th Avenue, New York, NY 10019', '(212) 555-0654', 'jobs@customercare.com', 'High school diploma or equivalent, excellent communication skills, customer service experience preferred, problem-solving abilities', '[]', 2);
